<a href="https://colab.research.google.com/github/beingshub02/25_days_of_Ml/blob/main/Day_ML_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Handling Categorical Data**

**5.1 Encoding Nominal Categorical Features**

*   Problem
*   You have a feature with nominal classes that has no intrinsic ordering (e.g., apple, pear,banana), You want to encode the feature into numerical values.



In [ ]:
# Import libraries
import pandas as pd
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

# Create feature
feature = pd.Series(['Apple', 'Pear', 'Orange', 'Pear'])

# Create one-hot encoder
one_hot = LabelBinarizer()

# One-hot encode feature
one_hot_encoded = one_hot.fit_transform(feature)

# View feature classes
print(one_hot.classes_)

# View encoded feature class
print(one_hot_encoded)

['Apple' 'Orange' 'Pear']
[[1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]


**5.2 Encoding Ordinal Categorical Features**



*   Problem
*   You have an ordinal categorical feature(e.g., high, medium, low), and you want to transform it into numerical values.



In [ ]:
# Load libraries
import pandas as pd

# Create features
dataframe = pd.DataFrame({'Score': ['Low', 'Low', 'Medium', 'Medium', 'High']})

# Create mapper
scale_mapper = {'Low':1,
                'Medium':2,
                'High':3}

# Replace feature values with scale
dataframe['Score'].replace(scale_mapper)

/tmp/ipykernel_477/2867375126.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataframe['Score'].replace(scale_mapper)


,Score
0,1
1,1
2,2
3,2
4,3


**5.3 Encoding Dictionaries of Features**

*   Problem
*   List item



In [ ]:
# Import library
from sklearn.feature_extraction import DictVectorizer

# Create dictionary
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

# Create dictionary vectorizer
dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary to feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

**5.4 Imputing Missing Class Values**

*   Problem
*   You have a categorical feature containing missing values that you want to replace with predicted values.



In [ ]:
# Load library
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# Create feature matrix with categorical feature
X = np.array([[0, 2.10, 1.45],
              [1, 1.18, 1.33],
              [0, 1.22, 1.27],
              [1, -0.21, -1.19]])

# Create feature matrix with missing values in the categorical feature
X_with_nan = np.array([[np.nan, 0.87, 1.31],
                      [np.nan, -0.67, -0.22]])

# Train KNN learner
clf = KNeighborsClassifier(3, weights='distance')
trained_model = clf.fit(X[:,1:], X[:,0])

# Predict class of missing values
imputed_values = trained_model.predict(X_with_nan[:,1:])

# Join column of predicted class with their other features
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))

# Join two feature matrices
np.vstack((X_with_imputed, X))

array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

**5.5 Handling Imbalanced classes**

*   Problem
*   You have a traget vector with highly imbalanced classes, and you want to make adjustments so that you can handle the class imbalance.



In [5]:
# Load library
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Load iris data
iris = load_iris()

# Create feature matrix
features = iris.data

# Create target vector
target = iris.target

# Remove first 40 observations
features = features[40:,:]
target = target[40:]

# Create binary target vector indicating if class 0
target = np.where((target == 0), 0, 1)

# Look at the imbalanced target vector
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])