<a href="https://colab.research.google.com/github/beingshub02/25_days_of_Ml/blob/main/ML_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Working with Vector, Matrices, and Arrays in NumPy**

**1.1 Creating a Vector **

*   Problem
*   You need to create a Vector




In [25]:
#load library
import numpy as np
#Create a vector as a row
Vector_colum = np.array([1,2,3])
#Create a vector as a column
vector_column = np.array([[1],
 [2],
  [3]])

 **1.2 Creating a Matrix **

*   Problem
*   You need to create a matrix



In [26]:
#Load library
import numpy as np
#create a matrix
matrix = np.array([[1,2],
 [1,2],
  [1,2]])

**1.3 Creating a Sparse matrix**


*   Problem
*   Given data with very few nonzeros values, you want to efficiently represent it.



In [27]:
#load libraries
import numpy as np
from scipy import sparse
#create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])
#create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

**1.4 Preallocationg NumPy Arrays**


*   Problem
*   You need to preallocate arraysof the a given size with some value.




In [28]:
#load library
import numpy as np
#Generate a vector of shape (1,5) containing all zeros
vector = np.zeros(shape=5)

#View the matrix
print(vector)

#Generate a matrix of shape (3,3) containing all ones
matrix = np.full(shape=(3,3), fill_value=1)

#View the vector
print(matrix)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**1.5 Selecting Elements**


*   Problem
*   You need to select one or more elements in a vector or matrix



In [29]:
#Load library
import numpy as np
#Create a row vector
vector = np.array([1,2,3,4,5,6])
#create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#select third element of vector
vector[2]

#select second row, second column
matrix[1,1]


np.int64(5)

**1.6 Describing a Matrix**

*   Problem
*   You want to describe the shape, size and dimensions of the matrix




In [30]:
#load library
import numpy as np
#Create matrix
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
#view number of rows and columns
matrix.shape
#view number of rows and cloumns
matrix.size
#View number of dimenions
matrix.ndim

2

**1.7 Applying Function over Each Element**


*   Problem
*   You want to apply some function to all elements in an array



In [31]:
#load library
import numpy as np
#Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# Create function that ads 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

**1.8 Finding the maximum and minimum values**

*   Problem
*   You need to find the maximum or minimum value in an array.



In [32]:
#Load Library
import numpy as np
# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
#Return maximum element
np.max(matrix)
#Return minimum element
np.min(matrix)

np.int64(1)

**1.9 Calculating the Average, Variance, and Standard Deviation**

*   Problem
*   You want to calculate some descriptive statistics about an array.




In [33]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# Return mean
np.mean(matrix)
# Return variance
np.var(matrix)
# Return standard deviation
np.std(matrix)

np.float64(2.581988897471611)

**1.10 Reshaping Arrays**


*   Problem
*   You want to change the shape (number of rows and columns ) of an array without changing the element values.

In [34]:
# Load library
import numpy as np

# Create 4*3 matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10,11,12]])
# Reshape matrix into 2*6 matrix
matrix.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**1.11 Transposing a Vector or Matrix**


*   Problem
*   You need to transpose a vector or matrix



In [35]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**1.12 Flattening a Matrix**


*   Problem
*   You need to transfer a matrix into a one-dimensional array.



In [36]:
# Load library
import numpy as np

# create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**1.13 Finding the Rank of a Matrix**


*   Problem
*   You need to know the rank of a matrix.



In [37]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,1,1],
                  [1,1,10],
                  [1,1,15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)


np.int64(2)

**1.14 Getting the Diagonal of a Matrix**


*   Problem
*   You need to get the diagonal element of a matrix.














In [38]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

**1.15 Calculating the Trace of a Matrix**


*   Problem
*   You need to calculate the trace of Matrix



In [39]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
# Return trace
matrix.trace()


np.int64(15)

**1.16 Calculating Dot Products**


*   Problem
*   You need to calculate the dot product of two vectors.







In [40]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)


np.int64(32)

**1.17 Adding and Subtracting Matrices**


*   Problem
*   You want to add or subtract two Matrices



In [41]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1,1,1],
                  [1,1,1],
                  [1,1,2]])
# Create matrix
matrix_b = np.array([[1,3,1],
                  [1,3,1],
                  [1,3,8]])
# Add two matrices
np.add(matrix_a, matrix_b)
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

**1.18 Multiplying Matrices**


*   Problem
*   You want to multiply two matrices



In [42]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1,1],
                     [1,2]])

# Create matrix
matrix_b = np.array([[1,3],
                     [1,2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)


array([[2, 5],
       [3, 7]])

**1.19 Inverting a matrix**


*   Problem
*   You want to calculate the inverse of a square matrix





In [43]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1,4],
                  [2,5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

**1.20 Generating Random values**


*   Problem
*   You want to generate pseudorandom values.




In [44]:
# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])